coverage:
  status:
    project:
      default:
        # Define the overall project coverage status
        target: auto
        threshold: 1%
        paths:
          - "pkg/"
    patch:
      default:
        # Define the patch coverage status (for pull requests)
        target: auto
        threshold: 1%
        paths:
          - "pkg/"

# Ignore coverage for files and pkg
ignore:
  - "pkg/datasets/gsm8k.go"
  - "pkg/datasets/hotpot_qa.go"
  - "examples/**"
  - "cmd/**"
  - "internal/**"
  - "test/**"
  - "*.md"
  - "*.yml"
  - "*.yaml"
  - "Makefile"
  - "LICENSE"

# Configure Codecov to only comment on pull requests if coverage decreases
comment:
  require_changes: false
