version: "2"
linters:
  default: none
  enable:
    - errcheck
    - godot
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    staticcheck:
      # QF1012 is a stylistic autofix suggestion ("Use fmt.Fprintf(...) instead of
      # WriteString(fmt.Sprintf(...))"). Enabling it currently produces broad
      # codebase-wide noise and blocks unrelated changes.
      checks:
        - -QF1012
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
